_core:
  default_config_hash: HENvUIeX6xNPGRB1w3z6rT9a71LM_hKXATF6XrM9WvM
smtp_on: true
smtp_host: localhost
smtp_hostbackup: ''
smtp_port: '1025'
smtp_protocol: standard
smtp_autotls: true
smtp_timeout: 50
smtp_username: souvikemailer@gmail.com
smtp_password: 'cahk midq sqla sncp'
smtp_from: souvikemailer@gmailer.com
smtp_fromname: 'Souvik Banerjee'
smtp_client_hostname: '0.0.0.0:1025'
smtp_client_helo: ''
smtp_allowhtml: '1'
smtp_test_address: dfkjghsdlfgsdfdj@gmail.com
smtp_reroute_address: ''
smtp_debugging: true
prev_mail_system: php_mail
smtp_keepalive: true
